# Generated by Django 3.1.13 on 2023-08-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0002_auto_20230831_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivedpermit',
            unique_together={('id',)},
        ),
    ]
